# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#  For correction purpose.
Ensure you always create new cell for your code, so that your answer won't override mine.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
fives = 5 * arr2
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create the following matrix:

array([0.01      , 0.03020408, 0.05040816, 0.07061224, 0.09081633,
       0.11102041, 0.13122449, 0.15142857, 0.17163265, 0.19183673,
       0.21204082, 0.2322449 , 0.25244898, 0.27265306, 0.29285714,
       0.31306122, 0.33326531, 0.35346939, 0.37367347, 0.39387755,
       0.41408163, 0.43428571, 0.4544898 , 0.47469388, 0.49489796,
       0.51510204, 0.53530612, 0.5555102 , 0.57571429, 0.59591837,
       0.61612245, 0.63632653, 0.65653061, 0.67673469, 0.69693878,
       0.71714286, 0.73734694, 0.75755102, 0.7777551 , 0.79795918,
       0.81816327, 0.83836735, 0.85857143, 0.87877551, 0.89897959,
       0.91918367, 0.93938776, 0.95959184, 0.97979592, 1.        ])

In [8]:
np.linspace(0.01,1,50)

array([0.01      , 0.03020408, 0.05040816, 0.07061224, 0.09081633,
       0.11102041, 0.13122449, 0.15142857, 0.17163265, 0.19183673,
       0.21204082, 0.2322449 , 0.25244898, 0.27265306, 0.29285714,
       0.31306122, 0.33326531, 0.35346939, 0.37367347, 0.39387755,
       0.41408163, 0.43428571, 0.4544898 , 0.47469388, 0.49489796,
       0.51510204, 0.53530612, 0.5555102 , 0.57571429, 0.59591837,
       0.61612245, 0.63632653, 0.65653061, 0.67673469, 0.69693878,
       0.71714286, 0.73734694, 0.75755102, 0.7777551 , 0.79795918,
       0.81816327, 0.83836735, 0.85857143, 0.87877551, 0.89897959,
       0.91918367, 0.93938776, 0.95959184, 0.97979592, 1.        ])

#### Create an array of 20 linearly spaced points between 0 and 1:

array([0.01      , 0.06210526, 0.11421053, 0.16631579, 0.21842105,
       0.27052632, 0.32263158, 0.37473684, 0.42684211, 0.47894737,
       0.53105263, 0.58315789, 0.63526316, 0.68736842, 0.73947368,
       0.79157895, 0.84368421, 0.89578947, 0.94789474, 1.        ])

In [10]:
np.linspace(0.01,1,20)

array([0.01      , 0.06210526, 0.11421053, 0.16631579, 0.21842105,
       0.27052632, 0.32263158, 0.37473684, 0.42684211, 0.47894737,
       0.53105263, 0.58315789, 0.63526316, 0.68736842, 0.73947368,
       0.79157895, 0.84368421, 0.89578947, 0.94789474, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [11]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [12]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[3,4]

20

20

In [21]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat[-1,1:]

array([22, 23, 24, 25])

array([22, 23, 24, 25])

### Now do the following

In [24]:
arr = np.random.randint(1,100,100)
arr

array([79,  7, 40, 87, 53, 80, 33,  5, 73, 91, 79, 42,  8, 60, 12, 58, 10,
       20, 44, 81,  3, 29, 58,  7, 99, 99,  8, 20, 44, 55, 32, 65, 28, 82,
        6, 74, 23, 82, 89, 72, 88, 38, 39, 39, 47, 16, 31, 37,  3,  4, 33,
       17, 90, 76, 35, 93, 94, 93, 22, 28, 82, 80, 86, 69, 15, 34, 67, 94,
       14, 17, 70, 86, 15, 89, 13, 67, 92, 38, 29, 77,  2, 67, 69,  2, 39,
       44, 75,  1, 29, 45, 91, 20, 79, 91, 22, 46, 10, 68, 71, 39])

#### Get all the element greater than 80 in the array (arr) above

array([88, 86, 91, 85, 86, 94, 93, 97, 98, 92, 90, 91, 99, 92, 86, 99, 86])

In [25]:
arr[arr > 80]

array([87, 91, 81, 99, 99, 82, 82, 89, 88, 90, 93, 94, 93, 82, 86, 94, 86,
       89, 92, 91, 91])

#### return all values that are even number and greater than 50

array([74, 88, 56, 74, 78, 86, 70, 86, 78, 72, 76, 94, 98, 78, 92, 90, 70,
       92, 86, 86, 66, 66, 68, 74])

In [27]:
arr[(arr % 2 == 0) & (arr > 50)]

array([80, 60, 58, 58, 82, 74, 82, 72, 88, 90, 76, 94, 82, 80, 86, 94, 70,
       86, 92, 68])

####  change the shape of the array to 10x10 matrix

array([[25, 74, 88, 69, 56, 51, 74, 48, 47, 29],
       [16, 11, 65,  4, 22, 78, 42, 39,  1, 86],
       [91, 79,  8, 51, 38, 10, 70, 41, 85, 28],
       [18, 31, 86, 32, 78, 18, 72, 27, 19, 71],
       [76, 26, 94, 39, 77, 93, 36, 14, 97,  1],
       [98, 77, 78, 92, 38, 44, 42, 77, 65, 90],
       [15, 32,  8, 91, 55, 12, 32,  8, 25, 99],
       [ 5, 70, 92, 86, 47, 34, 99, 86, 79,  4],
       [66,  6, 57, 75, 49,  8, 26, 47, 12, 24],
       [66, 59, 68, 42, 46, 22, 74,  7, 39, 36]])

In [29]:
arr = arr.reshape(10,10)
arr

array([[79,  7, 40, 87, 53, 80, 33,  5, 73, 91],
       [79, 42,  8, 60, 12, 58, 10, 20, 44, 81],
       [ 3, 29, 58,  7, 99, 99,  8, 20, 44, 55],
       [32, 65, 28, 82,  6, 74, 23, 82, 89, 72],
       [88, 38, 39, 39, 47, 16, 31, 37,  3,  4],
       [33, 17, 90, 76, 35, 93, 94, 93, 22, 28],
       [82, 80, 86, 69, 15, 34, 67, 94, 14, 17],
       [70, 86, 15, 89, 13, 67, 92, 38, 29, 77],
       [ 2, 67, 69,  2, 39, 44, 75,  1, 29, 45],
       [91, 20, 79, 91, 22, 46, 10, 68, 71, 39]])

#### what is the minimum value of the array arr?

1

In [31]:
arr.min()

1

#### what is the index of te minimum value of the array arr?

18

In [32]:
arr.argmin()

87

#### what is the maximum value of the array arr?

99

In [33]:
arr.max()

99

#### what is the index of te minimum value of the array arr?

69

In [34]:
arr.argmax()

24

# Great Job!