In [1]:
import numpy as np

### QUESTION 1

Write a python program that computes the determinant of a given matrix. Your program should prompt the user to enter the number of rows and columns they want the matrix to have.

NOTE: The number of rows and columns should be equal (as determinant only works for square matrix). Also, your program should allow the user to enter the values of the matrix.

Your program must be dynamic i.e. it must work for any n xn matrix

In [2]:
nrow = int(input("Enter the number of rows "))
ncol = int(input("Enter the number of columns "))
if (nrow == ncol):
    count = nrow * ncol
    i = 1
    lister = []
    while i <= count:
        ele = int(input("Enter a number "))
        lister.append(ele)
        i = i + 1
    
    arr = np.asarray(lister).reshape(nrow, ncol)
    
    # Compute the determinant
    
    det = np.linalg.det(arr)
    print("The Determinant of the \n {} is {}".format(arr, det))
else:
    print("Invalid input.\nThe number of rows and columns must be equal")

Enter the number of rows 2
Enter the number of columns 2
Enter a number 5
Enter a number 3
Enter a number 4
Enter a number 7
The Determinant of the 
 [[5 3]
 [4 7]] is 23.0


### QUESTION 2

Write a python program, leveraging on numpy library to solve system of linear equation. In this case, your program must also prompt the user to enter the values of the variables present in the equation.

# SYSTEM OF LINEAR EQUATION
suppose we<br> x + y + z = 19 <br>
           2x + 4y   = 2 <br>
           3x + 9y -3z = 4 <br>
 To solve the equation above we have to transform it to matrices.<br>
 By doing this we will have<br>
<b>Matrix A</b><br>[ [ 1, 1, 1 ]<br>
                  [ 2, 4, 0 ]<br>
                  [ 3, 9, -3 ] ]<br>
and a column<b> Vector B </b><br>
[ [ 19 ]<br>
[ 2 ]<br>
[ 4 ] ]<br>

We then compute the <b>unknown</b><br>[x,y,z]<br>
X = A(^-1)B

## The steps followed:
1. Get all values for <b>matrix A</b><br>
2. Then get all values for <b>column vector B</b> corresponding to each row in matrix A.<br>
3. Then solve by leveraging on numpy ability.<br>

In [4]:
def getMatrixA():
    try:
        print("==============================WElCOME TO SYSTEM OF LINEAR EQUATION.=========================")        
        mat = []
        rows = int(input("How many unknowns : "))
        cols = rows
        print("GETTING VALUES FOR MATRIX A ")
        for row in range(rows):
            mat.append([])
            values = input("Enter values for row {} seperated by comma (,) :  ".format(row)).split(',')
            if len(values) == cols:
                for i in values:
                    mat[row].append(int(i))
            else:
                print("Column doesn't match")
                break
    except ValueError as err:
        print(err)
        
    return mat

matrixA = getMatrixA() 
n = len(matrixA)

def getVectorB():
    try:
        matB = []
        for i in range(1,n+1):
            value = eval(input("Enter value for row {}, of the column vector:".format(i)))
            matB.append(value)
        return matB
    except ValueError as err:
        print(err)

matrixB = getVectorB()

A = np.asarray(matrixA) 
B = np.asarray(matrixB).reshape(n,1)

if np.linalg.det(A) == 0:
    print("Cannot compute solution for singular matrix")

else:

    A_inv = np.linalg.inv(A)


    X = np.linalg.solve(A_inv,B)

    print('A = \n', A)
    print('B = \n', B)


    print("The solution for the  equation is: \n",X)


==============================WElCOME TO SYSTEM OF LINEAR EQUATION.=========================
How many unknowns : 3
GETTING VALUES FOR MATRIX A 
Enter values for row 0 seperated by comma (,) :  1,1,1
Enter values for row 1 seperated by comma (,) :  3,6,7
Enter values for row 2 seperated by comma (,) :  2,5,8
Enter value for row 1, of the column vector:12
Enter value for row 2, of the column vector:5
Enter value for row 3, of the column vector:-4
A = 
 [[1 1 1]
 [3 6 7]
 [2 5 8]]
B = 
 [[12]
 [ 5]
 [-4]]
The solution for the  equation is: 
 [[13.]
 [38.]
 [17.]]


### HERE IS ANOTHER FORMAT...... without handling exceptions.

In [5]:
import numpy as  np

def getMatrix_A():
    print("WELCOME TO SYSTEM OF LINEAR EQUATION")
    matA = []
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of cols: "))
    if rows != cols:
        print("Number of columns must be equal to Number of rows")
    else:

        for row in range(rows):
            matA.append([])
            for col in range(cols):
                value = eval(input("Enter value for row {}, column {} of the matrix: ".format(row,col)))
                matA[row].append(value)
    return matA

matrixA = getMatrix_A()  
n = len(matrixA)


def getVector_B():
    matB = []
    for i in range(1,n+1):
        value = eval(input("Enter value for row {}, of the column vector:".format(i)))
        matB.append(value)
    return matB

      
matrixB = getVector_B()

   
A = np.asarray(matrixA) 
B = np.asarray(matrixB).reshape(n,1)

A_inv = np.linalg.inv(A)


X = np.linalg.solve(A_inv,B)

det = np.linalg.det(A)



print('A = \n', A)
print('B = \n', B)


print("The solution for the  equation is: \n",X)


WELCOME TO SYSTEM OF LINEAR EQUATION
Enter the number of rows: 3
Enter the number of cols: 3
Enter value for row 0, column 0 of the matrix: 1
Enter value for row 0, column 1 of the matrix: 1
Enter value for row 0, column 2 of the matrix: 1
Enter value for row 1, column 0 of the matrix: 3
Enter value for row 1, column 1 of the matrix: 6
Enter value for row 1, column 2 of the matrix: 7
Enter value for row 2, column 0 of the matrix: 2
Enter value for row 2, column 1 of the matrix: 5
Enter value for row 2, column 2 of the matrix: 8
Enter value for row 1, of the column vector:12
Enter value for row 2, of the column vector:5
Enter value for row 3, of the column vector:-4
A = 
 [[1 1 1]
 [3 6 7]
 [2 5 8]]
B = 
 [[12]
 [ 5]
 [-4]]
The solution for the  equation is: 
 [[13.]
 [38.]
 [17.]]


# THANK YOU FOR YOUR TIME